error: clean up and expose internally the error functions
Give some well-deserved clean-up to the error functions:

* Remove the unused kefir_vset_error() function.
* Make the names more consistent (prefix with "error").
* Pass prefix, then format, then args instead of format, prefix, args;
  all functions now get a prefix argument.
* Add the format((printf)) attributes wherever necessary.
* Reorder the functions correctly in the file.

Additionally, move the DEFINE_ERR_FUNCTIONS macro to the common internal
header, so that we can reuse it to declare the helpers in all files
(even those not related to parsing). Update header inclusion accordingly
in parsing-related files.

Signed-off-by: Quentin Monnet <quentin.monnet@netronome.com>