error: rework error messages management
Discard the whole error-in-a-buffer thing. Instead of maintaining an
internal buffer for the error messages, print to standard error output.
The kefir_strerror() and kefir_strerror_reset() functions disappear.

We add a new function kefir_set_print() API function to change the
printing function, so that users can fine-tune how messages are printed.

Bonus: Avoid appending a duplicate line break character when we hook
into libbpf error messages (to prefix them with a context tag).

Suggested by @kuba-moo.

Signed-off-by: Quentin Monnet <quentin.monnet@netronome.com>